//
//  MAP_NSBundle.h
//  mstapnext_injectable_ios
//
//  Stub generated by script on 12/14/2015.
//  Copyright (c) 2015 Mocana. All rights reserved.
//  Licensed to Microsoft under Contract #7267038.
//

/**
 * @file MAP_NSBundle.h
 *
 * Doc stub: Contains a stub declaration of interfaces (or categories) from
 * NSBundle.h.
 */

#include <TargetConditionals.h>
#import <Foundation/Foundation.h>

__attribute__ ((visibility ("default")))
@interface MAP_NSBundle : NSBundle

@end

