on:
  pull_request:
    branches:    
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Parse Version
        id: parse_version
        run: |
          version=$(echo "${{ github.event.pull_request.title }}" | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$")
          if [[ -z "$version" ]]; then
            echo "Version number could not be found"
            exit 1;
          fi
          echo "release_version=$version" >> "$GITHUB_ENV"
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.release_version }}
          release_name: Release ${{ env.release_version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
